apiVersion: v1
kind: Namespace
metadata:
  name: foo
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: foo
  name: foo
  namespace: foo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: foo
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: foo
    spec:
      containers:
      - image: httpd
        name: httpd
        resources: {}
        lifecycle:
          preStop:
            exec:
              command: ["sleep", "5"]  # Add a 5-second delay before termination
status: {}
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: foo
  namespace: foo
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app: foo